# Generated by Django 5.0.1 on 2025-11-17 22:12

import apps.game.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for players"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                            ("draw", "Draw"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "board",
                    models.JSONField(
                        default=list,
                        help_text="Board state as a list of 9 positions",
                        validators=[apps.game.validators.validate_board_state],
                    ),
                ),
                (
                    "current_turn",
                    models.CharField(
                        choices=[("X", "Player X"), ("O", "Player O")],
                        default="X",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player1",
                    models.ForeignKey(
                        help_text="Player X (starts first)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_player1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player O",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_player2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Position on the board (0-8)",
                        validators=[apps.game.validators.validate_board_position],
                    ),
                ),
                (
                    "symbol",
                    models.CharField(choices=[("X", "X"), ("O", "O")], max_length=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Move",
                "verbose_name_plural": "Moves",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["-created_at"], name="game_game_created_b8327b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["status"], name="game_game_status_295efa_idx"),
        ),
        migrations.AddIndex(
            model_name="move",
            index=models.Index(
                fields=["game", "created_at"], name="game_move_game_id_c26b34_idx"
            ),
        ),
    ]
